# Generated by Django 5.2.12 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_warranty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('PL', 'Paid Leave'), ('UL', 'Unpaid Leave'), ('ML', 'Maternity Leave'), ('PTL', 'Paternity Leave')], max_length=10),
        ),
    ]
