# Generated by Django 5.2.12 on 2026-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('PL', 'Paid Leave'), ('UL', 'Unpaid Leave'), ('MATERNITY_LEAVE', 'maternity_leave'), ('PATERNITY_LEAVE', 'paternity_leave')], max_length=100),
        ),
    ]
