# Generated by Django 5.2.12 on 2026-05-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_replacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='license_plate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='signature_img',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
