# Generated by Django 5.2.12 on 2026-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_employeepasswordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepasswordreset',
            old_name='Employee',
            new_name='employee',
        ),
    ]
