# Generated by Django 5.2.12 on 2026-05-21 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_employee_employeepasswordreset_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepasswordreset',
            name='otp',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeepasswordreset',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
