# Generated by Django 5.2.12 on 2026-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employeepasswordreset_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepasswordreset',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
