# Generated by Django 5.2.12 on 2026-05-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_employeepasswordreset_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePasswordReset',
        ),
    ]
