# Generated by Django 5.2.12 on 2026-05-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_employeeforgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeforgotpassword',
            old_name='email_id',
            new_name='email',
        ),
    ]
