# Generated by Django 5.2.12 on 2026-05-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
    ]
