# Generated by Django 5.2.12 on 2026-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_testimonial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
