# Generated by Django 5.2.12 on 2026-06-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_shipment_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('VOID', 'VOID'), ('PENDING', 'PENDING'), ('HOLD', 'HOLD')], default='PENDING', max_length=10),
        ),
    ]
