# Generated by Django 5.2.12 on 2026-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_warranty_warranty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
